version: '3'
services:
  app:
    build: ./Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
  rabbitmq:
    build: ./rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
