#server:
#  port: 9090
#  error:
#    include-message: always
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://containers-us-west-161.railway.app:6262/railway
#    password: pLEbhbMaizuODj6DskjX
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true
#  rabbitmq:
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 9090
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/manageequipment
    password: 0392338494
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbit:
  queue:
    save_request: save_request
    push_notification: push_notification
  exchange:
    manage_equipment: manage_equipment
  routing:
    save_request: save_request_routing_key
    push_notification: push_notification_routing_key
